name: test_reelease

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.2'
          elixir-version: '1.14.2'
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix rustler_precompiled.download ExDateUtil.Rrule --all
      - name: Publish package to hex.pm
        uses: wesleimp/action-publish-hex@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}